### ISSUE TITLE
Success message but no sound

### ISSUE THREAD

**Issue by hayukimori** [shindozk/yukufy#1]
During testing, I had a certain problem where, when using the `/play` command.
The bot entered the channel, show the song that would play in the chat, then a message that it was playing, but a few seconds later it would just sent `🔚 Music queue finished` and ended the connection with the voice channel.

![image](https://github.com/user-attachments/assets/736fa3d1-fdfb-4f37-9dab-d4b915c27df8)

**Comment by hayukimori** [comment]
Solution

The script needs to be run on a server/host, which is prepared for this type of script.

I was able to run it using nexcord

**Comment by shindozk** [comment]
*Fixed
